### ISSUE TITLE
Interior paths not generated

### ISSUE THREAD

**Issue by Hilldamn** [mkrabset/krabzcam#20]
When I import my SVG and select profile outside for cutting it only generates the paths for the outer squares and not the inner shapes. Not sure if this is a problem with the SVG file or if I didn't specify a parameter. Here is a zip file of the SVG and a screenshot of issue.
[map.svg.zip](https://github.com/mkrabset/krabzcam/files/7495488/map.svg.zip)
<img width="1262" alt="Screen Shot 2021-11-08 at 12 06 35 PM" src="https://user-images.githubusercontent.com/45794380/140712306-08ded071-ba9c-4d2b-982e-0d636684fb2e.png">

**Comment by mkrabset** [comment]
Hi, thanks for your input!
When creating profiles or pockets, all involved paths needs to be closed. 
All interior shapes in your drawing are open paths, so that is the reason.
I guess you need to close the open paths and edit them so the follow their perimeters.
(hope this makes sense :-) )

Best regards
Marius

**Comment by Hilldamn** [comment]
Yup, that was the issue. Thank you so much!
