### ISSUE TITLE
Possible to avoid G02 and G03 (arc moves)?

### ISSUE THREAD

**Issue by andrewerrington** [mkrabset/krabzcam#7]
Hello again,

Our machine is supposed to support G02 and G03, but it often rejects them for reasons I haven't yet determined.

Is it possible to have a checkbox under "Operations" to prevent G02 and G03 commands being generated? In other words, instead of generating a single command for a curve with I and J parameters, generate a series of commands for short lines which approximate the curve?

This may be a significant amount of work, and I am not sure how many people would benefit.

I will test the output of krabzcam on our machine and see if it works with G02 and G03.

Thank you.

**Comment by mkrabset** [comment]
G02/03 are a bit tricky, since they usually introduce a tiny error (due to rounding), and this error needs to be lower than what the cnc-controller is set up to tolerate.
But they also have great benefits, since the amount of gcode required is a lot less than what you would get with lines.
Krabzcam uses a lot of decimals in the gcode, so these errors should be quite small. 
Please test it out and let me know how it goes.
